In [1]:
import os
parent_path = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
os.chdir(parent_path)

In [2]:
from comchoice import voting
from comchoice import datasets

In [3]:
print("To check the library, you can use the help function:")
help(voting)

To check the library, you can use the help function:
Help on module comchoice.voting in comchoice:

NAME
    comchoice.voting

CLASSES
    builtins.object
        Voting

    class Voting(builtins.object)
     |  Voting(data)
     |
     |  Voting.
     |
     |  The class `Voting` defines rules to make collective decisions.
     |  It includes methods to calculate alternatives' ranking and some
     |  axiomatic properties in social choice theory.
     |
     |  Attributes
     |  ----------
     |  alternative: str, default="alternative"
     |      alternatives' unique identifier.
     |  party: str, default="party"
     |      Party's unique identifier. (Attribute used for proportional methods).
     |  rank: str, default="rank"
     |      Ranking of alternatives selected by a voter.
     |  show_rank: bool, default=True
     |      If the value is `true`, the ranking methods defined in `Voting`
     |      will include a column with the ranking of each alternative.
     |  voter: str, default="voter"
     |      Voter's unique identifier.
     |  voters: str, default="voters"
     |      If `voter` is not defined, and each row represents more than one voter,
     |      it includes the number of voters that selected the same ranking of alternatives.
     |
     |  Methods defined here:
     |
     |  __init__(self, data)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  black(self) -> pandas.core.frame.DataFrame
     |      Black procedure (1958).
     |
     |      Calculates winner of an election using Black procedure. First, the method calculates if there is a
     |      Condorcet winner. If there is a Condorcet winner, that alternative is the winner. Otherwise, the winner
     |      using Borda count is the winner.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          Election's winner using Black procedure.
     |
     |      References
     |      ----------
     |      Black, Duncan (1958). The theory of committees and elections. Cambridge: University Press.
     |
     |  borda(self, score='original') -> pandas.core.frame.DataFrame
     |      Borda Count (1784).
     |
     |      The Borda count is a voting method to rank alternatives.
     |      In an election, each voter gives a ranked-ordered list of their preferences.
     |      Then, it assigns the lowest score to the lowest-ranked alternative, increasing
     |      the score assigned until the alternative ranks first. The winner is the alternative with the most points.
     |
     |      The original version proposed by Borda for an election of n alternatives, assigns `n - 1`
     |      points to the alternative in the first place, `n - 2` to the alternative in the second place,
     |      and so on, until assigning 0 to the lowest-ranked alternative.
     |
     |      Parameters
     |      ----------
     |      score: {"original", "score_n", "dowdall"}, default="original"
     |          Method to calculate Borda score.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          Election results using Borda Count.
     |
     |      References
     |      ----------
     |      Borda, J. D. (1784). Mémoire sur les élections au scrutin. Histoire de l'Academie
     |      Royale des Sciences pour 1781 (Paris, 1784).
     |
     |  compare_methods(self, methods=['borda', 'k-approval', 'copeland', 'plurality']) -> pandas.core.frame.DataFrame
     |      Compares the ranking given to a alternative in different aggregation methods.
     |
     |      Parameters
     |      ----------
     |      methods : list of {"borda", "k-approval", "copeland", "plurality"}, optional:
     |          Methods to be compared. Values accepted are borda, k-approval, copeland, and plurality.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          DataFrame with a comparison of the methods defined. The first column represents the alternative, and the following ones represent each method being compared.
     |
     |  completeness(self) -> bool
     |      Completeness of data.
     |
     |      Verifies if each voter sets a ranking of alternatives.
     |      Required in voting methods that need a ranking of alternatives provided by each voter.
     |
     |      Returns
     |      -------
     |      bool:
     |          Boolean variable to indicate if the data is complete.
     |
     |  condorcet(self, weak=True)
     |      Condorcet winner (1785).
     |
     |      A Condorcet winner is the alternative who wins 100% of 1v1 elections regarding all
     |      the other alternatives running in the same election (under a plurality rule).
     |
     |      A weak Condorcet winner does not need to satisfy the rule of 100% of victories.
     |
     |      Parameters
     |      ----------
     |      weak: bool, default=True
     |          If the value is `true`, returns a weak Condorcet winner.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          Condorcet winner
     |
     |      References
     |      ----------
     |      de Condorcet, M. (1785), Essai sur l'Application de l'Analyse à la Probabilité des Décisions Rendues à la Pluralité des Voix. Paris: L'Imprimerie Royale.
     |
     |      Felsenthal, D.S., Tideman, N. Weak Condorcet winner(s) revisited. Public Choice 160, 313-326 (2014). https://doi.org/10.1007/s11127-014-0180-4
     |
     |  copeland(self) -> pandas.core.frame.DataFrame
     |      Copeland voting method (1951).
     |
     |      Each voter ranks alternatives by preference. Next, we sort alternatives by the
     |      number of times they beat another alternative in a pairwise comparison.
     |      The top-1 on Copeland's method is considered a weak Condorcet winner.
     |      Likewise, if in an election of `n` alternatives, a alternative beats `n - 1`
     |      alternatives in pairwise comparison scenarios, it is also considered a Condorcet winner.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          Election results using Copeland method.
     |
     |      References
     |      ----------
     |      Copeland, A.H. (1951). A “reasonable” social welfare function, mimeographed. In: Seminar on applications of mathematics to the social sciences. Ann Arbor: Department of Mathematics, University of Michigan.
     |
     |  copeland_matrix(self, n_votes=False)
     |
     |  cumulative(self) -> pandas.core.frame.DataFrame
     |      Cumulative Voting.
     |
     |      Calculates the cumulative score of each alternative.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          Election results using Cumulative Voting
     |
     |  dhondt(self, seats=1) -> pandas.core.frame.DataFrame
     |      D'Hondt (or Jefferson) method.
     |
     |      Calculates the number of elected alternatives of each party using the D'Hondt (or Jefferson) method.
     |
     |      Parameters
     |      ----------
     |      seats : int, default=1, optional:
     |          Number of seats to be assigned in the election.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          Summary with the seats of each party.
     |
     |  dowdall(self) -> pandas.core.frame.DataFrame
     |      Dowdall voting method (1971).
     |
     |      Dowdall is an alternative to Borda count, devised by Nauru's Secretary
     |      of Justice in 1971. As in Borda, each voter gives a ranking of alternatives.
     |      The first alternative gets 1 point, the 2nd alternative 1/2 points, and so on
     |      until the alternative ranked in the n position receives 1/n points.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          a ranking of alternatives using Dowdall.
     |
     |      References
     |      ----------
     |      Fraenkel, Jon; Grofman, Bernard (3 April 2014). "The Borda Count and its real-world alternatives: Comparing scoring rules in Nauru and Slovenia". Australian Journal of Political Science. 49 (2): 186-205. doi:10.1080/10361146.2014.900530
     |
     |  hare(self) -> pandas.core.frame.DataFrame
     |      Hare Rule (also called as Instant Runoff, Ranked-Choice Voting, and Alternative Vote)
     |
     |      Calculates the winner of an election. In each iteration,
     |      removes the alternative with the lowest score in a plurality rule,
     |      until to have a majority winner.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          The election's winner using Hare Rule.
     |
     |  k_approval(self, k=1) -> pandas.core.frame.DataFrame
     |      k-Approval voting method.
     |
     |      The method gives 1 if the alternative is ranked over or equal to k. Otherwise, the value given is 0.
     |
     |      Parameters
     |      ----------
     |      k (int, default=1, optional):
     |          Threshold to score alternatives with a value of 1.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          Election results using the k-approval method.
     |
     |      References
     |      ----------
     |
     |  kemeny_young(self, score_matrix=False)
     |      Kemeny-Young method.
     |
     |      The Kemeny-Young method is a voting method that uses preferential ballots
     |      and pairwise comparison to identify the most popular alternatives in an election.
     |
     |      Parameters
     |      ----------
     |      score_matrix : bool, default = False
     |          If the value is `true`, returns the score matrix.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          Election results using Kemeny-Young method.
     |
     |      References
     |      ----------
     |      John Kemeny, "Mathematics without numbers", Daedalus 88 (1959), pp. 577-591.
     |
     |      H. P. Young, "Optimal ranking and choice from pairwise comparisons", in Information pooling and group decision making edited by B. Grofman and G. Owen (1986), JAI Press, pp. 113-122.
     |
     |      H. P. Young and A. Levenglick, "A Consistent Extension of Condorcet's Election Principle", SIAM Journal on Applied Mathematics 35, no. 2 (1978), pp. 285-300.
     |
     |  loser(self, method='borda', n=1) -> pandas.core.frame.DataFrame
     |      Returns the loser of an election based on a voting method.
     |
     |      Parameters
     |      ----------
     |      method : str, default="borda"
     |      n : int, default=1
     |          Number of losers.
     |
     |      See Also
     |      --------
     |      winner: some other related function
     |
     |  negative(self) -> pandas.core.frame.DataFrame
     |      Negative Voting.
     |
     |      Calculates the score of each alternative using Negative Voting.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          Election results using Negative Voting.
     |
     |  plurality(self)
     |      Plurality Rule.
     |
     |      Each voter selects one alternative (or none if voters can abstain), and the alternative(s) with the most votes win.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          Election results using Plurality Rule.
     |
     |  ranking(self, method='plurality', **args) -> pandas.core.frame.DataFrame
     |      Calculates the ranking of alternatives usen a given voting method.
     |
     |      Parameters
     |      ----------
     |      method : {"borda", "copeland", "k-approval", "plurality"}, default="plurality"
     |          Method to be used for calculating the ranking.
     |      k : int, default=1
     |          Just valid for k-approval method.
     |      bootstrap : bool or int, default=False
     |          Number of bootstraps to calculate confidence interval.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          Ranking of alternatives calculated with the method defined.
     |
     |  score(self) -> pandas.core.frame.DataFrame
     |      Score Voting. (Also called as Range Voting, Utilitarian Voting).
     |
     |      In this method, voters give a score to each alternative. We average the scores,
     |      and the winner is the alternative with the highest score.
     |
     |      Returns
     |      -------
     |      pandas.DataFrame:
     |          Election results using Score Voting.
     |
     |  smith_set(self)
     |      Smith Set.
     |
     |      The Smith Set, Generalized Top-Choice Assumption (GETCHA), or Top Cycle,
     |      is the smallest non-empty set of alternatives in an election.
     |      Each member defeats every alternative outside the set in a pairwise election.
     |
     |      Returns
     |      -------
     |      list:
     |          alternatives that are part of the Smith Set.
     |
     |  winner(self, method='borda', n=1) -> pandas.core.frame.DataFrame
     |      Returns the winner of an election based on a voting method.
     |
     |      Parameters
     |      ----------
     |      method : str, default="borda"
     |      n : int, default=1
     |          Number of losers.
     |
     |      See Also
     |      --------
     |      loser: some other related function
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)

FILE
    /Users/cnavarreteliz/Projects/comchoice/comchoice/voting.py

## First, let's create an artificial election to analyse.

In [4]:
data = datasets.load_synthetic_election(n_alternatives=5, n_voters=100,
                                        alternatives = ["Maria","John","Alice","Alex","Ana"])
data.sort_values(by='voters', ascending=False).head()

                         rank  voters
45  John>Alex>Ana>Maria>Alice       4
2   Alex>Alice>John>Ana>Maria       3
73  Maria>John>Alex>Alice>Ana       3
30  Ana>Alex>Maria>John>Alice       3
0   Alex>Alice>Ana>John>Maria       2

<div class="alert alert-info">
We created an artificial election with 5 ordered alternatives in the first column, and 100 votes (sum of the second column). Based on this election, we can compute the possible winners using different methods.
</div>

In [5]:
# To do so, create the voting class 
vote = voting.Voting(data)

In [6]:
# Now, you can see a summary of the possible winners and rankings.
vote.compare_methods(methods=["borda", "k-approval", "copeland", "plurality"]).head()

  alternative  plurality
2       Ana          1
3      John          2
0      Alex          3
4     Maria          4
1     Alice          5

## Let's start with the condocert winner:

<div class="alert alert-info">
    <strong>Condorcet winner: </strong> is the alternative who would win in a pairwise comparison against each of the other alternatives. A weak condocert winner is the winner that win in most of the pairwise comparison.
</div>

<div class="alert alert-warning">
    <strong>To compute the condocert winner, you can call the .condocert() function from the Class Voting </strong> 
</div>

In [7]:
vote.condorcet()

                   alternative  value
0  Alex>Alice>Ana>John>Maria    0.0

<div class="alert alert-warning">
    <strong>The condocert winner will be the first element ranked by the Copeland method.</strong> 
</div>

In [8]:
vote.copeland().head()

                    alternative  value  rank
0   Alex>Alice>Ana>John>Maria    0.0     1
56  John>Ana>Maria>Alex>Alice    0.0     2
54  John>Ana>Alex>Maria>Alice    0.0     3
53  John>Ana>Alex>Alice>Maria    0.0     4
52  John>Alice>Maria>Ana>Alex    0.0     5

<div class="alert alert-info">
    <strong>Borda winner: </strong> is the alternative who was had higher number of votes, but it was not necessarily voted by majority. 
</div>

In [9]:
vote.borda().head()

  alternative  value  rank
0      Alex    210     1
2       Ana    210     2
3      John    200     3
4     Maria    198     4
1     Alice    182     5

<div class="alert alert-info">
    <strong>Black's procedure: </strong> if there is a Condorcet winner, then that alternative is the Condorcet winner. Otherwise, the winner is the Borda winner.
</div>

In [10]:
vote.black().head()

  alternative  value  rank
0      Alex    210     1

<div class="alert alert-info">
    <strong>K-approval winner: </strong> is the alternative who was approved by the majority (largest number of voters). This system allows people to approve k number of alternatives.
</div>

In [11]:
vote.k_approval(k=3).head()

  alternative  value  rank
0      Alex     64     1
4     Maria     62     2
2       Ana     61     3
3      John     60     4
1     Alice     53     5

<div class="alert alert-info">
    <strong> Comparing: </strong> We can observe that we have different rankings regardless of having the same winner. This means that the voting system might not change the winner but it will change the ranking.
</div>

In [12]:
vote.compare_methods(methods=["borda", "k-approval", "copeland", "plurality"]).sort_index()

  alternative  plurality
0      Alex          3
1     Alice          5
2       Ana          1
3      John          2
4     Maria          4